Update events.ts
Luzefiru/wuwatracker pull request #69
Opened 2024-06-26 06:00 UTC by PyrZern

Testing timeline events for Tower of Adversity and the Illusive Realm. Actual time might not be accurate :/

## Problem Context

Explain the **details** for making this change. What existing problem does the pull request solve?

## Solution

Please provide enough information so that others can review your pull request:

## Testing

Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

## Closing Issues

Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

2024-06-26 08:35 UTC, Luzefiru commented on events.ts
> +      endDate: '2024-06-26 03:59',
This should be `2024-06-27` according to [this page](https://wutheringwaves.fandom.com/wiki/Depths_of_Illusive_Realm).

2024-06-26 08:37 UTC, Luzefiru commented on events.ts
> +      img: 'https://i.gyazo.com/b4e79733131536f81036e57d556ce091.jpg',
If you have the new image of the Illusive Realm (the Scar one?), it would be a better fit.

2024-06-26 08:38 UTC, Luzefiru requested changes
I left a few comments after cross-checking with my server time (SEA, UTC+8). Once those are resolved, LGTM!

2024-06-26 16:38 UTC, PyrZern commented on events.ts
> +      img: 'https://i.gyazo.com/b4e79733131536f81036e57d556ce091.jpg',
I don't have it yet.  But an image is easily changed once 1.1 hits.

2024-06-26 17:28 UTC, Luzefiru commented on events.ts
> +      img: 'https://i.gyazo.com/b4e79733131536f81036e57d556ce091.jpg',
Oh alright. Could you please update your fork by synchronizing it with the main repository and changing the time? There should be a button somewhere [here](https://github.com/PyrZern/wuwatracker/tree/patch-1) to sync. Otherwise, let me know if you need help.

![image](https://github.com/Luzefiru/wuwatracker/assets/105530193/58a41353-56df-4f2d-b9af-586241a311d3)

2024-06-28 05:56 UTC, antisocial93 commented
i suppose there is no need in this pr anymore due to done commits? although making the ToA a recurring event is a good idea, its timer set on 2 weeks, as far as i know, what do you think, @Luzefiru?

2024-06-28 05:59 UTC, Luzefiru commented
> i suppose there is no need in this pr anymore due to done commits? although making the ToA a recurring event is a good idea, its timer set on 2 weeks, as far as i know, what do you think, @Luzefiru?

Right, we've updated it already. I'll need to change the implementation a bit to keep recurring events like ToA in the same row in the timeline. I'll be closing this PR now. Thanks @PyrZern & @antisocial93!

2024-06-28 05:59 UTC, closed without merging